[package]
name = "jellyroller"
version = "1.1.5"
edition = "2024"
description = "The CLI Jellyfin Controller Utility for Linux and Windows."
repository = "https://github.com/LSchallot/JellyRoller"
readme = "README.md"
license = "GPL-2.0"
keywords = ["jellyroller", "jellyfin"]
categories = ["command-line", "jellyfin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.45" 
clap = { version = "4.6.4", features = ["derive"] }
confy = "2.0.0"
serde = "1.0.229"
serde_derive = "1.0.229"
serde_json = "1.0.151"
reqwest = { version = "0.12.28", features = ["blocking", "json", "rustls-tls"], default-features = false }
rpassword = "7.5.4"
url = "2.5.8"
comfy-table = "7.2.2"   
image = "0.25.10"
base64 = "0.22.1"
csv = "1.4.0"
clap_complete = "4.6.8"
prop_reader = "0.2.0"
